Q1: Questions on Basic NumPy Array
(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])

reversed_arr = arr[::-1]

print(reversed_arr)

[5 4 6 3 2 1]


  (b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods


In [ ]:
import numpy as np

# Define the 2D array
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Flatten the array using the flatten() method
flattened_array1 = array1.flatten()

print(flattened_array1)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Flatten the array using the ravel() method
flattened_array2 = array1.ravel()

print(flattened_array2)

[1 2 3 2 4 5 1 2 3]
[1 2 3 2 4 5 1 2 3]


(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])


In [ ]:
import numpy as np

# Define the array
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

# Find the most frequent value
unique, counts = np.unique(x, return_counts=True)
most_frequent_value = unique[np.argmax(counts)]

# Find the indices of the most frequent value
indices = np.where(x == most_frequent_value)[0]

print("Most frequent value in x:", most_frequent_value)
print("Indices of the most frequent value in x:", indices)

Most frequent value in x: 1
Indices of the most frequent value in x: [0 5 7 8 9]


(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


In [ ]:
import numpy as np

# Define the matrix
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
sum_all_elements = np.sum(gfg)
print("Sum of all elements:", sum_all_elements)

# ii. Sum of all elements row-wise
sum_row_wise = np.sum(gfg, axis=1)
print("Sum of all elements row-wise:", sum_row_wise)

# iii. Sum of all elements column-wise
sum_column_wise = np.sum(gfg, axis=0)
print("Sum of all elements column-wise:", sum_column_wise)

Sum of all elements: 45
Sum of all elements row-wise: [[14]
 [16]
 [15]]
Sum of all elements column-wise: [[20  9 16]]


  (f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

In [ ]:
import numpy as np

# Define the matrix
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Sum of diagonal elements
sum_diagonal = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal)

# ii. Eigenvalues of the matrix
eigenvalues, _ = np.linalg.eig(n_array)
print("Eigenvalues of the matrix:", eigenvalues)

# iii. Eigenvectors of the matrix
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print("Eigenvectors of the matrix:\n", eigenvectors)

# iv. Inverse of the matrix
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of the matrix:\n", inverse_matrix)

# v. Determinant of the matrix
determinant = np.linalg.det(n_array)
print("Determinant of the matrix:", determinant)


Sum of diagonal elements: 176
Eigenvalues of the matrix: [98.16835147 28.097044   49.73460452]
Eigenvectors of the matrix:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of the matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of the matrix: 137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]


In [ ]:
import numpy as np

# Define matrices p and q
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

# Matrix multiplication
product = np.dot(p, q)
print("Product of p and q:\n", product)

# Flatten matrices
p_flat = p.flatten()
q_flat = q.flatten()

# Calculate covariance matrix
cov_matrix = np.cov(p_flat, q_flat)
print("Covariance matrix between flattened p and q:\n", cov_matrix)

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])

# Matrix multiplication
product = np.dot(p, q)
print("Product of p and q:\n", product)

# Flatten matrices
p_flat = p.flatten()
q_flat = q.flatten()

# Calculate covariance matrix
cov_matrix = np.cov(p_flat, q_flat)
print("Covariance matrix between flattened p and q:\n", cov_matrix)

Product of p and q:
 [[16 19]
 [26 31]]
Covariance matrix between flattened p and q:
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Product of p and q:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance matrix between flattened p and q:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?


In [ ]:
import numpy as np

# Define the matrices
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# i. Inner Product
inner_product = np.dot(x, y.T)  # Transpose y to align dimensions for multiplication
print("Inner product:\n", inner_product)

# ii. Outer Product
x_flat = x.flatten()
y_flat = y.flatten()
outer_product = np.outer(x_flat, y_flat)
print("Outer product:\n", outer_product)

# iii. Cartesian Product
X, Y = np.meshgrid(x_flat, y_flat)
cartesian_product = np.vstack([X.ravel(), Y.ravel()]).T
print("Cartesian product:\n", cartesian_product)


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.
iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [ ]:
import numpy as np

# Array for part (a)
array = np.array([[1, -2, 3], [-4, 5, -6]])

# (a) i. Element-wise absolute value
absolute_array = np.abs(array)
print("Element-wise absolute value:\n", absolute_array)

# (a) ii. Percentiles
percentiles_flattened = np.percentile(array.flatten(), [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)

print("Percentiles of flattened array (25th, 50th, 75th):", percentiles_flattened)
print("Percentiles for each column (25th, 50th, 75th):\n", percentiles_columns)
print("Percentiles for each row (25th, 50th, 75th):\n", percentiles_rows)

# (a) iii. Mean, Median, and Standard Deviation
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_dev_flattened = np.std(array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("Mean of flattened array:", mean_flattened)
print("Median of flattened array:", median_flattened)
print("Standard deviation of flattened array:", std_dev_flattened)

print("Mean of each column:", mean_columns)
print("Median of each column:", median_columns)
print("Standard deviation of each column:", std_dev_columns)

print("Mean of each row:", mean_rows)
print("Median of each row:", median_rows)
print("Standard deviation of each row:", std_dev_rows)

# Array for part (b)
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# (b) Floor, Ceiling, Truncated, and Rounded values
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]
Percentiles of flattened array (25th, 50th, 75th): [-3.5 -0.5  2.5]
Percentiles for each column (25th, 50th, 75th):
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row (25th, 50th, 75th):
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean of flattened array: -0.5
Median of flattened array: -0.5
Standard deviation of flattened array: 3.8622100754188224
Mean of each column: [-1.5  1.5 -1.5]
Median of each column: [-1.5  1.5 -1.5]
Standard deviation of each column: [2.5 3.5 4.5]
Mean of each row: [ 0.66666667 -1.66666667]
Median of each row: [ 1. -4.]
Standard deviation of each row: [2.05480467 4.78423336]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
i. Sorted array
ii. Indices of sorted array
iii. 4 smallest elements
iv. 5 largest elements
(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
i. Integer elements only
ii. Float elements only


In [ ]:
import numpy as np

# (a) For the array [10, 52, 62, 16, 16, 54, 453]
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i. Sorted array
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# ii. Indices of sorted array
indices_of_sorted_array = np.argsort(array)
print("Indices of sorted array:", indices_of_sorted_array)

# iii. 4 smallest elements
four_smallest_elements = np.partition(array, 4)[:4]
print("4 smallest elements:", four_smallest_elements)

# iv. 5 largest elements
five_largest_elements = np.partition(array, -5)[-5:]
print("5 largest elements:", five_largest_elements)

# (b) For the array [1.0, 1.2, 2.2, 2.0, 3.0, 2.0]
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i. Integer elements only
integer_elements = array[array.astype(int) == array]
print("Integer elements only:", integer_elements)

# ii. Float elements only
float_elements = array[array != array.astype(int)]
print("Float elements only:", float_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [16 10 16 52]
5 largest elements: [ 16  52  62  54 453]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)


In [ ]:
from PIL import Image
import numpy as np

def img_to_array(path):
    # Open the image file
    with Image.open(path) as img:
        # Convert the image to a NumPy array
        img_array = np.array(img)
        print(img_array)

        # Determine if the image is RGB or grayscale
        if len(img_array.shape) == 3:
            # RGB image
            if img_array.shape[2] == 3:
                # Save the RGB image array to a text file
                np.savetxt('image_rgb.txt', img_array.reshape(-1, 3), fmt='%d', delimiter=',')
                print("Saved RGB image data to 'image_rgb.txt'")
            elif img_array.shape[2] == 4:
                # RGBA image (though not requested, for completeness)
                np.savetxt('image_rgba.txt', img_array.reshape(-1, 4), fmt='%d', delimiter=',')
                print("Saved RGBA image data to 'image_rgba.txt'")
        elif len(img_array.shape) == 2:
            # Grayscale image
            np.savetxt('image_grey.txt', img_array, fmt='%d', delimiter=',')
            print("Saved grayscale image data to 'image_grey.txt'")
        else:
            print("Unsupported image format.")

# Example usage:
img_to_array('/content/Screenshot 2024-07-31 150903.png')


[[[255  10   4 255]
  [255  10   6 255]
  [255  10   6 255]
  ...
  [169  24  34 255]
  [169  24  34 255]
  [171  23  34 255]]

 [[254  10   5 255]
  [253  11   6 255]
  [253  11   6 255]
  ...
  [169  24  34 255]
  [169  24  34 255]
  [171  23  34 255]]

 [[253  11   6 255]
  [253  11   6 255]
  [252  11   6 255]
  ...
  [169  24  34 255]
  [169  24  34 255]
  [171  23  34 255]]

 ...

 [[242   4   9 255]
  [243   5  10 255]
  [243   5  10 255]
  ...
  [122  19  11 255]
  [122  19  11 255]
  [122  18  11 255]]

 [[242   4   9 255]
  [243   5  10 255]
  [243   5  10 255]
  ...
  [121  20  11 255]
  [121  20  11 255]
  [122  19  10 255]]

 [[242   4   9 255]
  [243   5  10 255]
  [243   5  10 255]
  ...
  [121  21  11 255]
  [121  20  10 255]
  [121  20  10 255]]]
Saved RGBA image data to 'image_rgba.txt'
